config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  root 'pages#index'

  resources :subscriptions
  resources :oportunities
  resources :companies
  resources :categories
  resources :customers
  # archivo de rutas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/oportunity.rb
class Oportunity < ApplicationRecord
  belongs_to :company
  belongs_to :category
end

app/controllers/oportunities_controller.rb
class OportunitiesController < ApplicationController
  before_action :set_oportunity, only: [:show, :edit, :update, :destroy]

  # GET /oportunities
  # GET /oportunities.json
  def index
    @oportunities = Oportunity.all
  end

  # GET /oportunities/1
  # GET /oportunities/1.json
  def show
  end

  # GET /oportunities/new
  def new
    @oportunity = Oportunity.new
  end

  # GET /oportunities/1/edit
  def edit
  end

  # POST /oportunities
  # POST /oportunities.json
  def create
    @oportunity = Oportunity.new(oportunity_params)

    respond_to do |format|
      if @oportunity.save
        format.html { redirect_to @oportunity, notice: 'Oportunity was successfully created.' }
        format.json { render :show, status: :created, location: @oportunity }
      else
        format.html { render :new }
        format.json { render json: @oportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oportunities/1
  # PATCH/PUT /oportunities/1.json
  def update
    respond_to do |format|
      if @oportunity.update(oportunity_params)
        format.html { redirect_to @oportunity, notice: 'Oportunity was successfully updated.' }
        format.json { render :show, status: :ok, location: @oportunity }
      else
        format.html { render :edit }
        format.json { render json: @oportunity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oportunities/1
  # DELETE /oportunities/1.json
  def destroy
    @oportunity.destroy
    respond_to do |format|
      format.html { redirect_to oportunities_url, notice: 'Oportunity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oportunity
      @oportunity = Oportunity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oportunity_params
      params.require(:oportunity).permit(:name, :description, :budget, :money, :published_date, :deadline, :result_date, :company_id, :category_id, :status)
    end
end

app/helpers/oportunities_helper.rb
module OportunitiesHelper
end

app/views/oportunities/_form.html.erb
<%= simple_form_for(@oportunity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :budget %>
    <%= f.input :money %>
    <%= f.input :published_date %>
    <%= f.input :deadline %>
    <%= f.input :result_date %>
    <%= f.association :company %>
    <%= f.association :category %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/oportunities/edit.html.erb
<h1>Editing Oportunity</h1>

<%= render 'form', oportunity: @oportunity %>

<%= link_to 'Show', @oportunity %> |
<%= link_to 'Back', oportunities_path %>

app/views/oportunities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oportunities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Budget</th>
      <th>Money</th>
      <th>Published date</th>
      <th>Deadline</th>
      <th>Result date</th>
      <th>Company</th>
      <th>Category</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oportunities.each do |oportunity| %>
      <tr>
        <td><%= oportunity.name %></td>
        <td><%= oportunity.description %></td>
        <td><%= oportunity.budget %></td>
        <td><%= oportunity.money %></td>
        <td><%= oportunity.published_date %></td>
        <td><%= oportunity.deadline %></td>
        <td><%= oportunity.result_date %></td>
        <td><%= oportunity.company %></td>
        <td><%= oportunity.category %></td>
        <td><%= oportunity.status %></td>
        <td><%= link_to 'Show', oportunity %></td>
        <td><%= link_to 'Edit', edit_oportunity_path(oportunity) %></td>
        <td><%= link_to 'Destroy', oportunity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oportunity', new_oportunity_path %>

app/views/oportunities/new.html.erb
<h1>New Oportunity</h1>

<%= render 'form', oportunity: @oportunity %>

<%= link_to 'Back', oportunities_path %>

app/views/oportunities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @oportunity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @oportunity.description %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @oportunity.budget %>
</p>

<p>
  <strong>Money:</strong>
  <%= @oportunity.money %>
</p>

<p>
  <strong>Published date:</strong>
  <%= @oportunity.published_date %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @oportunity.deadline %>
</p>

<p>
  <strong>Result date:</strong>
  <%= @oportunity.result_date %>
</p>

<p>
  <strong>Company:</strong>
  <%= @oportunity.company %>
</p>

<p>
  <strong>Category:</strong>
  <%= @oportunity.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @oportunity.status %>
</p>

<%= link_to 'Edit', edit_oportunity_path(@oportunity) %> |
<%= link_to 'Back', oportunities_path %>